# Generated by Django 3.2.4 on 2021-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название ленты')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр ленты')),
                ('trailer', models.TextField(verbose_name='Вставка трейлера <iframe>')),
                ('description', models.TextField(verbose_name='Описание ленты')),
                ('mpaa', models.CharField(max_length=10, verbose_name='Возрастные ограничения')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата показа')),
                ('price', models.PositiveIntegerField(verbose_name='Цена билета')),
                ('format', models.CharField(max_length=10, verbose_name='Формат ленты')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_time', to='afisha.cinema', verbose_name='Лента')),
            ],
            options={
                'verbose_name': 'Время показа',
                'verbose_name_plural': 'Время показа',
                'ordering': ['datetime'],
            },
        ),
    ]
