# Generated by Django 3.2.4 on 2021-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['title'], 'verbose_name': 'Лента', 'verbose_name_plural': 'Ленты'},
        ),
    ]
