# Generated by Django 3.2.4 on 2021-06-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_alter_cinema_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='duration',
            field=models.CharField(default=1, max_length=50, verbose_name='Длительность ленты'),
            preserve_default=False,
        ),
    ]
