# Generated by Django 3.2.4 on 2021-06-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_cinema_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='source',
            field=models.CharField(default=1, max_length=200, verbose_name='Ссылка на источник'),
            preserve_default=False,
        ),
    ]
